import {
  CARDS_COUNT_TO_ADD_SMALL_SCREEN,
  CARDS_COUNT_TO_ADD_MEDIUM_SCREEN,
  CARDS_COUNT_TO_ADD_LARGE_SCREEN,
  CARDS_COUNT_TO_ADD_EXTRA_LARGE_SCREEN,
  SMALL_SCREEN_WIDTH,
  MEDIUM_SCREEN_WIDTH,
  LARGE_SCREEN_WIDTH,
  EXTRA_LARGE_SCREEN_WIDTH,
} from './globalVariables';

export default function getAddCountMovies(width) {
  if (width <= SMALL_SCREEN_WIDTH) return CARDS_COUNT_TO_ADD_SMALL_SCREEN;
  if (width <= MEDIUM_SCREEN_WIDTH) return CARDS_COUNT_TO_ADD_MEDIUM_SCREEN;
  if (width <= LARGE_SCREEN_WIDTH) return CARDS_COUNT_TO_ADD_LARGE_SCREEN;
  if (width <= EXTRA_LARGE_SCREEN_WIDTH)
    return CARDS_COUNT_TO_ADD_EXTRA_LARGE_SCREEN;
  return CARDS_COUNT_TO_ADD_EXTRA_LARGE_SCREEN;
}
