import {
  INITIAL_CARDS_COUNT_SMALL_SCREEN,
  INITIAL_CARDS_COUNT_MEDIUM_SCREEN,
  INITIAL_CARDS_COUNT_LARGE_SCREEN,
  INITIAL_CARDS_COUNT_EXTRA_LARGE_SCREEN,
  SMALL_SCREEN_WIDTH,
  MEDIUM_SCREEN_WIDTH,
  LARGE_SCREEN_WIDTH,
  EXTRA_LARGE_SCREEN_WIDTH,
} from './globalVariables';

export default function getInitialCountMovies(width) {
  if (width <= SMALL_SCREEN_WIDTH) return INITIAL_CARDS_COUNT_SMALL_SCREEN;
  if (width <= MEDIUM_SCREEN_WIDTH) return INITIAL_CARDS_COUNT_MEDIUM_SCREEN;
  if (width <= LARGE_SCREEN_WIDTH) return INITIAL_CARDS_COUNT_LARGE_SCREEN;
  if (width <= EXTRA_LARGE_SCREEN_WIDTH)
    return INITIAL_CARDS_COUNT_EXTRA_LARGE_SCREEN;
  return INITIAL_CARDS_COUNT_EXTRA_LARGE_SCREEN;
}
